version: '3.8'

# ==========================================
# Production MEV Searcher Dashboard Deployment
# Complete Django Application with All Services
# ==========================================

services:
  # ==========================================
  # Complete MEV Dashboard (All-in-One Container)
  # ==========================================
  mev-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mev_dashboard_prod
    restart: unless-stopped

    # Security
    security_opt:
      - no-new-privileges:true

    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
        reservations:
          cpus: '2.0'
          memory: 4G

    # Environment configuration
    env_file:
      - .env.production
    environment:
      - DJANGO_SETTINGS_MODULE=mev_dashboard.settings
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/mev_dashboard
      - REDIS_URL=redis://localhost:6379/0
      - SECRET_KEY=${SECRET_KEY:-django-insecure-production-key-change-this}
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - LOG_LEVEL=info

    # Networking
    ports:
      - "80:80"      # Nginx web server
      - "8000:8000"  # Django development server
      - "5432:5432"  # PostgreSQL
      - "6379:6379"  # Redis

    # Volumes for persistent data
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - redis_data:/data
      - mev_logs:/app/logs
      - mev_media:/app/media
      - mev_data:/app/data

    # Health checks
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

    # Labels for orchestration
    labels:
      - "com.mev.service=dashboard"
      - "com.mev.version=1.0.0"
      - "com.mev.type=complete"

    networks:
      - mev_network

# ==========================================
# Networks
# ==========================================
networks:
  mev_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# ==========================================
# Volumes
# ==========================================
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  mev_logs:
    driver: local
  mev_media:
    driver: local
  mev_data:
    driver: local