global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mev-searcher'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - '/etc/prometheus/alerts.yml'

# Scrape configurations
scrape_configs:
  # MEV Searcher metrics
  - job_name: 'mev-searcher'
    static_configs:
      - targets: ['mev-searcher:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
